config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'service#index'
  get 'service/next_call', :controller => 'service', :action => 'next_call', :as => 'next_call'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController
    # before_action Client.new unless @request
    def index(url = 'https://api.edamam.com/api/recipes/v2?type=public&q=chicken&app_id=7d00fbca&app_key=aff00390c873981b10c794bc3c3f1756%09')
        request = Client.new(url)
        @response_body = request.fetch_from_api

        respond_to do |format|
            format.html
            if @response_body
                format.json{
                    render :json => @response_body
                  }
            else
                format.json {
                    render :json => @response_body.errors, status: :unprocessable_entity
                }
            end
          end
    end

    def next_call
        request = Client.new(params[:url])
        @response_body = request.fetch_from_api
        
        respond_to do |format|
            format.html
            if @response_body
                format.json{
                    render :json => @response_body
                  }
            else
                format.json {
                    render :json => @response_body.errors, status: :unprocessable_entity
                }
            end
          end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client.rb
require 'uri'
require 'net/http'
require 'json'
require 'pry'
require 'rest-client'

class Client
    def initialize(url)
        @request = RestClient.get url, { accept: :json }
    end

    def fetch_from_api
        result = []
        @next_page = JSON.parse(@request.body)['_links']['next']['href']
        @second_request = NextClient.new(@next_page).second_request if @next_page
        result.push(JSON.parse(@request.body), JSON.parse(@second_request))
    end
end

app/helpers/next_client.rb
require 'uri'
require 'net/http'
require 'json'
require 'pry'
require 'rest-client'

class NextClient
    attr_reader :second_request
    def initialize(url)
        @second_request = RestClient.get url, { accept: :json }
    end

    # def second_request
    #     @second_request.body
    # end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AscentProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/service/index.html.erb
<% @response_body.first['hits'].each do |recipe| %>
    <div> <img src=<%= recipe['recipe']['images']['SMALL']['url'] %> alt="recipe">  </div>
<% end %>

<% @response_body.second['hits'].each_with_index do |recipe, index| %>
    <% if index < 10 %> 
    <div> <img src=<%= recipe['recipe']['images']['SMALL']['url'] %> alt="recipe">  </div>
    <% else %>
    <%= nil %>
    <% end %>
<% end %>

<%= link_to "Click Me", next_call_path(url: @response_body.second['_links']['next']['href']) %>

app/views/service/next_call.html.erb
<% @response_body.first['hits'].each do |recipe| %>
    <div> <img src=<%= recipe['recipe']['images']['SMALL']['url'] %> alt="recipe">  </div>
<% end %>

<% @response_body.second['hits'].each_with_index do |recipe, index| %>
    <% if index < 10 %> 
    <div> <img src=<%= recipe['recipe']['images']['SMALL']['url'] %> alt="recipe">  </div>
    <% else %>
    <%= nil %>
    <% end %>
<% end %>

<%= link_to "Click Me", next_call_path(url: @response_body.second['_links']['next']['href']) %>